export const GET_COMMENTS = 'GET_COMMENTS'
export const GET_COMMENTS_DONE = 'GET_COMMENTS_DONE'
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED'

export const POST_COMMENT = 'POST_COMMENT'
export const POST_COMMENT_DONE = 'POST_COMMENT_DONE'
export const POST_COMMENT_FAILED = 'POST_COMMENT_FAILED'
